### ISSUE TITLE
[Addition] Raknetify

### ISSUE THREAD

**Issue by DuendeInexistente** [TheUsefulLists/UsefulMods#102]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

Raknetify

### What is your mod's main version?

1.17.1 - 1.19.2 (Fabric)
Also has versions for velocity and bungeecord (same mc versions)

### Input a link to your suggested mod. Make sure it isn't hosted on a site listed on StopModReposts.

https://modrinth.com/mod/raknetify

### What is your reasoning for including this mod?

(Alt link: https://github.com/RelativityMC/raknetify )
Allows users to use raknet to connect to servers, which improves network performance. Gives significant boosts on bad connections.

### (OPTIONAL) Give some extra information about the mod.

The version picker is missing 1.19

**Comment by lrmtheboss** [comment]
Does it need to be installed on both sides or just the client?
