### ISSUE TITLE
[Addition] 1.12.2 燐/Hesperus phosphor fork

### ISSUE THREAD

**Issue by Armagedon13** [TheUsefulLists/UsefulMods#115]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

燐/Hesperus

### What is your mod's main version?

1.12.X

### Input a link to your suggested mod. Make sure it isn't hosted on a site listed on StopModReposts.

https://www.curseforge.com/minecraft/mc-mods/hesperus

### What is your reasoning for including this mod?

Hesperus is a continuation of the abandoned [Phosphor Forge Edition](https://www.curseforge.com/minecraft/mc-mods/phosphor-forge/), aiming to fix crashes and mod conflicts.

In addition to the original mod's improvement and optimization to the vanilla lighting system, this fork had:

Fixed a [crash](https://github.com/jbredwards/Fluidlogged-API/issues/75) with [Fluidlogged API](https://www.curseforge.com/minecraft/mc-mods/fluidlogged-api/)
Fixed a rare crash with [Simple Text Overlay](https://www.curseforge.com/minecraft/mc-mods/simpletextoverlay)
Probably fixed a strange conflict with [Witchery: Resurrected](https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fwitchery.msrandom.net%252fhome)
 

This mod was based on [embeddedt](https://www.curseforge.com/members/embeddedt/projects)'s [fork](https://github.com/embeddedt/phosphor-forge112) of phosphor, so it has some degree of compatibility to [Dynamic Lighting](https://www.curseforge.com/minecraft/mc-mods/dynamic-lights), but the performance may be poor.

**Comment by NordicGamerFE** [comment]
Added in dev
