### ISSUE TITLE
[Addition] SelectiveEntityRemoval

### ISSUE THREAD

**Issue by x3rmination** [TheUsefulLists/UsefulMods#119]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

SelectiveEntityRemoval

### What is your mod's main version?

Other (Fabric)

### Input a link to your suggested mod. Make sure it isn't hosted on a site listed on StopModReposts.

https://www.curseforge.com/minecraft/mc-mods/selective-entity-removal-fabric

### What is your reasoning for including this mod?

Allows the user to modify the distance at which each entity renders, helpful for situations such as mob switches, large amounts of entities. As of 1.19 Selective Entity Removal supports other modded entities, however versions 1.18 and below only support vanilla.

**Comment by NordicGamerFE** [comment]
I noticed you are the creator, Any particular reason you don't have modded entities for versions below 1.18?

**Comment by x3rmination** [comment]
Yeah, the reason for that is because the config api I am using, cloth config, has two modules. The one I used in versions 1.18 and below allowed the config to be easier to create, however all the entities had to be hardcoded. For the 1.19 version I used the manual config api and that allowed to create a config entry for every mob included modded ones.

**Comment by NordicGamerFE** [comment]
Added in dev
