### ISSUE TITLE
[Addition] Canary (1.18.2 + 1.19.2)

### ISSUE THREAD

**Issue by alexhowell610** [TheUsefulLists/UsefulMods#124]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

Canary

### What is your mod's main version?

1.18.X (Forge)

### Input a link to your suggested mod. Make sure it isn't hosted on a site listed on StopModReposts.

https://www.curseforge.com/minecraft/mc-mods/canary

### What is your reasoning for including this mod?

It is a fork of Lithium with patches backported from the 1.19 version to the 1.18 version. It also fixes many of the issues that Radium Reforged hasn't addressed.

The author also says that in the future they want to add their own performance improvements not found in Lithium/Radium Reforged.

**Comment by brucethemoose** [comment]
One quirk is that the mod just went closed source.

**Comment by alexhowell610** [comment]
> One quirk is that the mod just went closed source.

He claims that its only temporary until he's finished but I do agree that it's odd

**Comment by brucethemoose** [comment]
> > One quirk is that the mod just went closed source.
> 
> He claims that its only temporary until he's finished but I do agree that it's odd

If he makes another release while the code is still closed source, that would violate Lithium's license.

But if its just temporary till the next release... thats still odd, but fine.

**Comment by Atlantispy** [comment]
It's back to being open source
