### ISSUE TITLE
[Addition] Let Me Despawn

### ISSUE THREAD

**Issue by frikinjay** [TheUsefulLists/UsefulMods#127]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

Let Me Despawn

### What is your mod's main version?

1.18.X (Fabric)

### Input a link to your suggested mod. Make sure it isn't hosted on a site listed on StopModReposts.

https://www.curseforge.com/minecraft/mc-mods/let-me-despawn

### What is your reasoning for including this mod?

Helps with lag caused by accidental persistent mobs. Will save the players and server owners a lot of headache.

### (OPTIONAL) Give some extra information about the mod.

Doesnt break any mod as far as I am aware.

**Comment by lrmtheboss** [comment]
Did you mean to close this?

**Comment by frikinjay** [comment]
I have a habit of going through stale issues and closing if unnecessary, mightve been it

**Comment by lrmtheboss** [comment]
alright I'll reopen this issue to be checked if its done or not

**Comment by NordicGamerFE** [comment]
Fixed in dev

**Comment by frikinjay** [comment]
Was going through the list to get some mods, noticed I couldnt find lmd, is it on a different page I am unaware of?
