### ISSUE TITLE
[Addition] World Pregenerators

### ISSUE THREAD

**Issue by Speiger** [TheUsefulLists/UsefulMods#137]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

Chunk Pregenerator

### What is your mod's main version?

Other (Forge)

### What is your mod's other versions?

1.8.X or earlier, 1.12.X, 1.15.X (Forge), 1.16.X (Forge), 1.18.X (Forge), 1.19.X (Forge)

### What is your mod's type?

Enhancement

### What side dose your mod need to run on?

Both

### Input a link to your suggested mod.

https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator

### What is your reasoning for including this mod?

Worldgen lag is a real issue. Even in Singleplayer, and worldpregeneration is actually a really important thing you should do.
This can turn it from "unplayable" to "playable" especially if your core count (including threads) is stuck at 4 or less or the CPU isn't the newest anymore... And even then its suggested to do so.

That's why I am suggestion ChunkPregenerator.
Which supports 1.4.7-1.7.x-1.8.9-1.10.x-1.11.x-1.12.x-1.14.x-1.15x-1.16x-1.18x-1.19.x

Also another mod that I would suggest is [Chunky](https://www.curseforge.com/members/pop4959/projects)
Which is another pregenerator that provides a lot of performance gains and covers
forge-fabric-customservers

while chunkpregenerator is dedicated for forge. 

### (OPTIONAL) Give some extra information about the mod.

Chunk Pregenerator is a tool for generating your world before you actually play it.
It also includes maintenance tools such as:
- Chunk Deletion/Trimming
- Performance Tracking (up to 1.12)
- World Maintenance tools (up to 1.12)
- Retro-generation that isn't relying on the Player Itself.
- Harddrive protection (1.14 or newer where it becomes nessesary)
- Memory Leak fixes that become apparent when pregeneration.

And a few other things.

**Comment by NordicGamerFE** [comment]
I've added your mod to performance mods as i think that is a better fit then Enhancement. Love your mods, Keep up the good work :D

**Comment by Speiger** [comment]
@NordicGamerFE 
Small extra note since i saw this.
Know issues + Fixes are actually tracked by myself.
Here you find both lists.
1.12 or older: https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/issues/1
1.14 or newer: https://github.com/TinyModularThings/Chunk-Pregenerator-Issue-Tracker/issues/2
