### ISSUE TITLE
[Correction] AnimFix + Triangulator

### ISSUE THREAD

**Issue by MachinegunMarty** [TheUsefulLists/UsefulMods#140]
### Checklist

- [X] I've checked that this correction is valid and accurate.
- [X] I've checked that this correction has not already been suggested.

### What mod is this correction for?

AnimFix + Triangulator

### What section(s) of the list is this correction for?

Performance

### What version(s) dose this correction apply to?

1.8.X or earlier, Other (Forge)

### What needs correcting?

I was downloading the performance mods for Forge 1.7.x and saw that AnimFix and Triangulator got merged into a new mod called " FalseTweaks:  https://modrinth.com/mod/falsetweaks

### Input relevant link(s) which can be used to verify the correction.

Link to authors merge comment: https://github.com/FalsePattern/FalseTweaks/releases/tag/2.0.0-alpha0002

**Comment by NordicGamerFE** [comment]
Fixed in dev.
