### ISSUE TITLE
1.19.2 NoTimeOutNoMore

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TheUsefulLists/UsefulMods#143]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

NoTimeOutNoMore

### What is your mod's main version?

1.19.X (Forge)

### What is your mod's other versions?

1.16.X (Forge), 1.17.X (Forge), 1.18.X (Forge)

### What is your mod's type?

Bugfix

### What side dose your mod need to run on?

Server

### Input a link to your suggested mod.

https://www.curseforge.com/minecraft/mc-mods/notimeoutnomore

### What is your reasoning for including this mod?

I want to add this mod because it is obscured by its name but is actually very helpful.

### (OPTIONAL) Give some extra information about the mod.

Right now you cannot change time out delay for forge 1.19.2 without a mod and this the only mod out that does this. Larger modpacks will benefit from this mod. I have a kitchen sink pack that can sometimes delay updates but not crash and this kind of mod has in fact helps quite a bit. Let's give it a slot ;)

**Comment by NordicGamerFE** [comment]
Added in dev
