### ISSUE TITLE
[Addition] [Perf] [Forge and Fabric] [1.19.2-1.18.2] Smooth Chunk Save

### ISSUE THREAD

**Issue by Raft08** [TheUsefulLists/UsefulMods#144]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

Server Performance - Smooth Chunk Save

### What is your mod's main version?

1.19.X (Forge)

### What is your mod's other versions?

1.18.X (Forge)

### What is your mod's type?

Preformance

### What side dose your mod need to run on?

Server

### Input a link to your suggested mod.

https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save

### What is your reasoning for including this mod?

Saves chunks continuously over time, reducing server lag and preventing lagspikes from saving too many chunks at once.

### (OPTIONAL) Give some extra information about the mod.

Is on fabric too

**Comment by NordicGamerFE** [comment]
Added in dev
