### ISSUE TITLE
[Software Addition] Crafty Controller

### ISSUE THREAD

**Issue by RMednis** [TheUsefulLists/UsefulMods#145]
### Checklist

- [X] I've checked that my software suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this software hasn't already been suggested.

### What is your software's name?

Crafty Controller

### What operating systems dose this software works on?

Windows 11, Windows 10, Windows 8/8.1, MacOS, Ubuntu, Debain, Arch Linux, Fedora, Other Linux

### Input a link to your suggested software.

https://craftycontrol.com/

### What is your reasoning for including this software?

Crafty is a web interface and server management platform for minecraft servers. It's fully open source and licenesed under GPL3, the full source code is available here:

https://gitlab.com/crafty-controller/crafty-4

Blurb from their website: 
```Crafty Controller is a feature rich panel that allows you to create and run servers, manage players, run commands, change server settings, view and edit server files, and make backups.```

**Comment by NordicGamerFE** [comment]
Added in dev
