### ISSUE TITLE
[Software Addition] Prism Launcher

### ISSUE THREAD

**Issue by TayouVR** [TheUsefulLists/UsefulMods#146]
### Checklist

- [X] I've checked that my software suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this software hasn't already been suggested.

### What is your software's name?

Prism Launcher

### What operating systems dose this software works on?

Windows 11, Windows 10, Windows 8/8.1, Windows 7, MacOS, Ubuntu, Debain, Arch Linux, Fedora, Other Linux

### Input a link to your suggested software.

https://github.com/PrismLauncher/PrismLauncher, https://prismlauncher.org/

### What is your reasoning for including this software?

it is a minecraft launcher, which many people use. 
It is also the go-to way of installing minecraft on steam deck.

### (OPTIONAL) Give some extra information about the software.

In addition the software list could maybe use some more info on it, I made this list a few months back and there are still missing fields, but maybe some of the information there could be useful to extend your list: https://gist.github.com/TayouVR/ed585459737fc5a0afa2b02eb10ce78b

**Comment by NordicGamerFE** [comment]
Would you like to work on our launcher lists directly?

**Comment by TayouVR** [comment]
I am not sure i'd feel comfortable operating on this list directly. 
If you like I can PR changes for it though, when I get the time.

**Comment by lrmtheboss** [comment]
Feel free to open a pr anytime. any help is greatly appreciated

**Comment by lrmtheboss** [comment]
done in pr #150
