### ISSUE TITLE
[Addition] Add Cyanide (Fabric)

### ISSUE THREAD

**Issue by Fnige** [TheUsefulLists/UsefulMods#148]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

Cyanide

### What is your mod's main version?

1.19.X (Fabric)

### What is your mod's other versions?

1.17.X (Fabric), 1.18.X (Fabric)

### What is your mod's type?

Enhancement

### What side dose your mod need to run on?

Both

### Input a link to your suggested mod.

https://www.curseforge.com/minecraft/mc-mods/cyanide-fabric

### What is your reasoning for including this mod?

It makes datapack related issues readable, also funny error recovery

### (OPTIONAL) Give some extra information about the mod.

There is a forge version too, but thats already covered in #134

**Comment by FnigePython** [comment]
Im 90% sure its both, _might_ be server only

Not sure how to tell without it being on modrinth
