### ISSUE TITLE
[Addition] Cull Clouds

### ISSUE THREAD

**Issue by Dronatar** [TheUsefulLists/UsefulMods#149]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

Cull Clouds

### What is your mod's main version?

1.19.X (Fabric)

### What is your mod's type?

Preformance

### What side dose your mod need to run on?

Client

### Input a link to your suggested mod.

https://modrinth.com/mod/cullclouds

### What is your reasoning for including this mod?

Fabric mod that adds a small optimization improves clouds culling way to not render parts which you cant see to increase fps

**Comment by NordicGamerFE** [comment]
Added in dev
