### ISSUE TITLE
[Correction] Canary Incompatibility

### ISSUE THREAD

**Issue by jussme** [TheUsefulLists/UsefulMods#151]
### Checklist

- [X] I've checked that this correction is valid and accurate.
- [X] I've checked that this correction has not already been suggested.

### What mod is this correction for?

Canary

### What section(s) of the list is this correction for?

Performance

### What version(s) dose this correction apply to?

1.19.X (Fabric)

### What needs correcting?

Canary conflicts with Apotheosis. Fixed when Canary was deleted from server mods.

### Input relevant link(s) which can be used to verify the correction.

![image](https://user-images.githubusercontent.com/30532641/202255503-a0b6d0d5-1c76-4109-b697-ab9e2612435f.png)

**Comment by NordicGamerFE** [comment]
Canary is for forge so i gonna assume that is what you mean

**Comment by NordicGamerFE** [comment]
Fixed in dev

**Comment by SettingDust** [comment]
It's not a conflict. Wrong incompatibility. Works fine.
