### ISSUE TITLE
[Correction] KubeJS for Fabric

### ISSUE THREAD

**Issue by MicrolemurDev** [TheUsefulLists/UsefulMods#155]
### Checklist

- [X] I've checked that this correction is valid and accurate.
- [X] I've checked that this correction has not already been suggested.

### What mod is this correction for?

KubeJS

### What section(s) of the list is this correction for?

Other

### What version(s) dose this correction apply to?

1.16.X (Fabric), 1.18.X (Fabric), 1.19.X (Fabric)

### What needs correcting?

KubeJS is listed for Modpack Tools as Forge only. This is not the case as it is usable on Fabric on both Curseforge and Modrinth (both links are seen below with the mod pages).

### Input relevant link(s) which can be used to verify the correction.

- https://modrinth.com/mod/kubejs
- https://www.curseforge.com/minecraft/mc-mods/kubejs
- https://github.com/KubeJS-Mods/KubeJS/tree/eol/1.16

### (OPTIONAL) Any extra information about the correction.

This is all the sources I could find that showed that it supported Fabric. I am sure this is sufficient for showing every version supported.

**Comment by NordicGamerFE** [comment]
I am aware this is just part 1 of a update that will go over many parts, modpack tool mods was one of the things I added but didn't work much on. most of my time went into download options and licenses. Thanks for the issue tho
