### ISSUE TITLE
CensoredASM - Dead url link

### ISSUE THREAD

**Issue by Irritated-Badger** [TheUsefulLists/UsefulMods#158]
### Checklist

- [X] I've checked that this correction is valid and accurate.
- [X] I've checked that this correction has not already been suggested.

### What mod is this correction for?

CensoredASM

### What section(s) of the list is this correction for?

Performance

### What version(s) dose this correction apply to?

1.12.X

### What needs correcting?

It appears Curseforge has finally killed CensoredASM. 

### Input relevant link(s) which can be used to verify the correction.

I've been digging for the Github, but my Googlefu has failed me.

**Comment by NordicGamerFE** [comment]
I will check on it later on their GitHub its being updated, and there is talk of more versions. the link will get updated once a dev version gets pushed as I am working on the new link system for all versions and categories

**Comment by lrmtheboss** [comment]
The CF link works fine, I will look into adding their GitHub link along with the CF link
https://github.com/LoliKingdom/LoliASM
