### ISSUE TITLE
[Addition] NormalASM

### ISSUE THREAD

**Issue by SuperStormer** [TheUsefulLists/UsefulMods#159]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

NormalASM

### What is your mod's main version?

1.12.X

### What is your mod's type?

Preformance

### What side dose your mod need to run on?

Both

### Input a link to your suggested mod.

https://www.curseforge.com/minecraft/mc-mods/normalasm

### What is your reasoning for including this mod?

Optimize RAM Usage

### (OPTIONAL) Give some extra information about the mod.

rebranded fork of CensoredASM
incompat with VanillaFix, TexFix, CensoredASM

**Comment by GalaxySynth** [comment]
https://github.com/TheUsefulLists/UsefulMods/issues/60#issuecomment-1085609985

If this is the case then why is CensoredASM still here?

**Comment by Radplay** [comment]
NormalASM was removed from CurseForge and the last commit was almost a year ago. CensoredASM meanwhile had several updates since then. I'd say it's safe to close this.
