### ISSUE TITLE
[Addition] [Perf] [Forge and Fabric] [1.19.2-1.18.2] Smooth Chunk Save (Reopened)

### ISSUE THREAD

**Issue by Raft08** [TheUsefulLists/UsefulMods#174]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

Smooth Chunk Save

### What is your mod's main version?

1.19.X (Forge)

### What is your mod's other versions?

1.18.X (Forge), 1.18.X (Fabric), 1.19.X (Fabric)

### What is your mod's type?

Preformance

### What side dose your mod need to run on?

Server

### Input a link to your suggested mod.

https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save

### What is your reasoning for including this mod?

Saves chunks continuously over time, reducing server lag and preventing lagspikes from saving too many chunks at once.

### (OPTIONAL) Give some extra information about the mod.

I already posted this addition it has been added, but sinds the remake of the github (Much better then before) it has been removed, is there a reason?

**Comment by NordicGamerFE** [comment]
Still is on the list.

**Comment by Raft08** [comment]
It is but the 1.18 version has been removed
