### ISSUE TITLE
[Addition] Adaptive Performance Tweaks

### ISSUE THREAD

**Issue by seriousfreezing** [TheUsefulLists/UsefulMods#179]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

Adaptive Performance Tweaks

### What is your mod's main version?

1.19.X (Forge)

### What is your mod's other versions?

1.16.X (Forge)

### What is your mod's type?

Preformance

### What side dose your mod need to run on?

Both

### Input a link to your suggested mod.

https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks

### What is your reasoning for including this mod?

I just want to know, why wasn't this mod placed as performance? Does it really give more performance? Or does it just do some tweaking or fixbugging?

**Comment by Raft08** [comment]
Adaptive performance tweaks only needs server side to work it's written in the description of the curseforge project, And the spawn mod breaks a litle bit the spawn it needs tweaking without tweaking it's hard to even find a passive mob, and it can break some farm with the spawn rules else it's a good mod, and note that it replaces 'Clumps' and 'Get It Together, Drops!'

**Comment by seriousfreezing** [comment]
So it is only worthwhile if it is placed on the server side? Does it help in cases where the game crashes for a short time out of nowhere?

**Comment by Raft08** [comment]
Only if you play in single player, else you don't need it on the client

**Comment by seriousfreezing** [comment]
Sounds like a good one for me, since I play with modpack with 160 fashion and singleplayer! But why is it not in the performance mods list, even with some annotation?

**Comment by Raft08** [comment]
Nope it's not I don't know why, I learned about it with a incompatibilty with Dynamic View in the 1.18 performance modlist
