### ISSUE TITLE
1.12.2 Universal Tweaks

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TheUsefulLists/UsefulMods#188]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

Universal Tweaks 

### What is your mod's main version?

1.12.X

### What is your mod's other versions?

1.12.X

### What is your mod's type?

Bugfix

### What side dose your mod need to run on?

Both

### Input a link to your suggested mod.

https://www.curseforge.com/minecraft/mc-mods/universal-tweaks

### What is your reasoning for including this mod?

I just found it today and it seems to be a dev hellbent on making 1.12.2 as stable as humanly possible in large scale mod environments.

**Comment by lrmtheboss** [comment]
Already has been added
