### ISSUE TITLE
[Correction] Better Biome Blend is no longer incompatible with Sodium

### ISSUE THREAD

**Issue by Ste-Mich** [TheUsefulLists/UsefulMods#190]
### Checklist

- [X] I've checked that this correction is valid and accurate.
- [X] I've checked that this correction has not already been suggested.

### What mod is this correction for?

Better Biome Blend

### What section(s) of the list is this correction for?

Performance

### What version(s) dose this correction apply to?

1.18.X (Fabric), 1.19.X (Fabric)

### What needs correcting?

Better Biome Blend is now compatible with Sodium. I tested this myself. Compatibility was added in 1.18.2-1.3.5 as is stated on their [modrinth](https://modrinth.com/mod/better-biome-blend) page.

### Input relevant link(s) which can be used to verify the correction.

https://modrinth.com/mod/better-biome-blend

**Comment by NBZion** [comment]
@NordicGamerFE
