### ISSUE TITLE
[Addition] ModernFix for 1.18.x /1.19.x forge list  

### ISSUE THREAD

**Issue by hampop** [TheUsefulLists/UsefulMods#196]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

ModernFix 

### What is your mod's main version?

1.16.X (Forge)

### What is your mod's other versions?

1.18.X (Forge), 1.19.X (Forge)

### What is your mod's type?

Preformance

### What side dose your mod need to run on?

Both

### Input a link to your suggested mod.

https://github.com/embeddedt/ModernFix https://www.curseforge.com/minecraft/mc-mods/modernfix

### What is your reasoning for including this mod?

Reduces startup and world load time

**Comment by JustFoxx** [comment]
also fabric

**Comment by lrmtheboss** [comment]
done
