### ISSUE TITLE
[Addition]

### ISSUE THREAD

**Issue by PLG2012** [TheUsefulLists/UsefulMods#202]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

Mine 

### What is your mod's main version?

1.8.X or earlier

### What is your mod's type?

Other

### What side dose your mod need to run on?

Both

### Input a link to your suggested mod.

Github

### What is your reasoning for including this mod?

Idk

**Comment by hankjelino** [comment]
bro where is the link for the mod

**Comment by lrmtheboss** [comment]
this addition request isn't valid. you didn't provide a link to the mod and valid reason to add it. feel free to reopen this request once you have updated it with the requested info
