### ISSUE TITLE
[Addition] Rhodium (Forge 1.16.x-1.19.x)

### ISSUE THREAD

**Issue by chadzar** [TheUsefulLists/UsefulMods#203]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

Rhodium

### What is your mod's main version?

1.19.X (Forge)

### What is your mod's other versions?

1.16.X (Forge), 1.17.X (Forge), 1.18.X (Forge), 1.19.X (Forge)

### What is your mod's type?

Preformance

### What side dose your mod need to run on?

Client

### Input a link to your suggested mod.

https://modrinth.com/mod/rhodium

### What is your reasoning for including this mod?

Optimizes DataFixerUpper, based on LazyDFU

### (OPTIONAL) Give some extra information about the mod.

"In comparison to other mods, Rhodium has the primary advantage of being simple, safe and having a low impact on the game."

**Comment by lrmtheboss** [comment]
What dose "low impact to the game" mean exactly?  it dose not any game mechanics? it has very little performance impact?

**Comment by chadzar** [comment]
I Don't know exactly, I'm not the mod owner
I Just noticed this mod makes my game load 10 seconds faster than LazyDFU

**Comment by lrmtheboss** [comment]
> I Don't know exactly, I'm not the mod owner I Just noticed this mod makes my game load 10 seconds faster than LazyDFU

is that with mods that add stuff like AE2 or Mekenism, or just with performance mods?

**Comment by NordicGamerFE** [comment]
Will not add as its a direct copy of Lazy DataFixerUpper

**Comment by NordicGamerFE** [comment]
![image](https://github.com/TheUsefulLists/UsefulMods/assets/18188155/fa12152c-f5e1-40e1-b598-8a14f5bf64f8)
