### ISSUE TITLE
Known incompatibility for Debugify: JEI

### ISSUE THREAD

**Issue by PingWine** [TheUsefulLists/UsefulMods#205]
### Checklist

- [X] I've checked that this correction is valid and accurate.
- [X] I've checked that this correction has not already been suggested.

### What mod is this correction for?

Debugify

### What section(s) of the list is this correction for?

Performance

### What version(s) dose this correction apply to?

1.18.X (Forge)

### What needs correcting?

You should add JEI to Debugify known incompatibilities as it partly breaks the search function

### Input relevant link(s) which can be used to verify the correction.

https://github.com/mezz/JustEnoughItems/issues/2801#issuecomment-1103781736

**Comment by PingWine** [comment]
> I believe you mean bug fixes as the category/section. It is not in the forge list for 1.18, did you mean fabric or 1.19?

I my bad, I didn't notice it was under fabric. Haven't tested the issue on fabric but I'm pretty sure it's the same there

**Comment by lrmtheboss** [comment]
Before we add something as an incompatibility we'll need evidence.
