### ISSUE TITLE
[Correction] Essentials

### ISSUE THREAD

**Issue by SomeCasualChu** [TheUsefulLists/UsefulMods#206]
### Checklist

- [X] I've checked that this correction is valid and accurate.
- [X] I've checked that this correction has not already been suggested.

### What mod is this correction for?

Essentials

### What section(s) of the list is this correction for?

Bugfixes

### What version(s) dose this correction apply to?

Not applicable

### What needs correcting?

The Essentials mod link actually redirects to a TP called PvP Essentials (the creator also has a different username from the one stated in Bugfixes) which, obviously, is not applicable to the Bugfixes category.

### Input relevant link(s) which can be used to verify the correction.

https://modrinth.com/resourcepack/essentials

**Comment by lrmtheboss** [comment]
You didn't specify what versions this correction applies to, so what versions does it apply to?

**Comment by lrmtheboss** [comment]
Fixed
