### ISSUE TITLE
[Addition] Nvidium [Fabric 1.19.4]

### ISSUE THREAD

**Issue by Cirvel** [TheUsefulLists/UsefulMods#208]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

Nvidium

### What is your mod's main version?

1.19.X (Fabric)

### What is your mod's type?

Preformance

### What side dose your mod need to run on?

Client

### Input a link to your suggested mod.

https://modrinth.com/mod/nvidium

### What is your reasoning for including this mod?

Nvidium is an alternate rendering backing for sodium, it uses cutting edge nvidia features to render huge amounts of terrain geometry at very playable framerates.

### (OPTIONAL) Give some extra information about the mod.

- ARR License
- Open source
- Requires sodium and an nvidia gtx 1600 series or newer to run (turning + architecture)
- Incompatible with Iris

This mod is in **very early alpha**, expect many issues and crashes (including system crashes)

**Comment by NordicGamerFE** [comment]
Added, Thanks for the suggestion.
