### ISSUE TITLE
[Addition] Embeddium

### ISSUE THREAD

**Issue by Poopooracoocoo** [TheUsefulLists/UsefulMods#251]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

Embeddium

### What is your mod's main version?

1.20.X (Forge)

### What is your mod's other versions?

1.16.X (Forge), 1.18.X (Forge), 1.19.X (Forge)

### What is your mod's type?

Preformance

### What side dose your mod need to run on?

Client

### Input a link to your suggested mod.

https://modrinth.com/mod/embeddium https://www.curseforge.com/minecraft/mc-mods/embeddium

### What is your reasoning for including this mod?

It's a fork of Sodium based on Rubidium. It focuses on mod compatibility

**Comment by lrmtheboss** [comment]
fixed by #257
