### ISSUE TITLE
[Correction] Nothirium mod incompatibilities in 1.12 Performance

### ISSUE THREAD

**Issue by victorguima** [TheUsefulLists/UsefulMods#258]
### Checklist

- [X] I've checked that this correction is valid and accurate.
- [X] I've checked that this correction has not already been suggested.

### What mod is this correction for?

Nothirium

### What section(s) of the list is this correction for?

Performance

### What version(s) does this correction apply to?

1.12.X

### What needs correcting?

Incompatibilities are listed as Unknown, but there's a small list in the mod page.
The list is:
Full Incompatibilities
- FarPlane2
- LittleTiles
- Albedo
- Colored Lux

Partial Incompatibilities
- Optifine: Make sure that 'Smart Animations' is disabled in the graphics settings. Also custom block render layer from Optifine won't work with Nothirium.
- VanillaFix: Make sure that 'textureFixes' is disabled in the VanillaFix config.
- CensoredASM: Make sure that 'onDemandAnimatedTextures' is disabled in the CensoredASM/LoliASM config.

### Input relevant link(s) which can be used to verify the correction.

https://www.curseforge.com/minecraft/mc-mods/nothirium

**Comment by lrmtheboss** [comment]
fixed in commit 003a86c
