### ISSUE TITLE
[Addition] Guns in Minecraft

### ISSUE THREAD

**Issue by skanda890** [TheUsefulLists/UsefulMods#266]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

Guns 

### What is your mod's main version?

1.8.X or earlier

### What is your mod's type?

Preformance

### What side dose your mod need to run on?

Both

### Input a link to your suggested mod.

https://github.com/Mojang/bedrock-samples/issues/31

### What is your reasoning for including this mod?

Some people may like guns in Minecraft

**Comment by lrmtheboss** [comment]
This issue is invalid, you have linked to a Mojang repo and not a mod. This type of mod is also not relevant to our list here at TUL

**Comment by skanda890** [comment]
Oh, Okay.
