### ISSUE TITLE
[Addition] Emotional Damage Level

### ISSUE THREAD

**Issue by skanda890** [TheUsefulLists/UsefulMods#268]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

EMOTIONAL DAMAGE 

### What is your mod's main version?

1.20.X (Forge)

### What is your mod's other versions?

1.19.X (Forge), 1.19.X (Fabric)

### What is your mod's type?

Preformance

### What side dose your mod need to run on?

Client

### Input a link to your suggested mod.

https://github.com/Mojang/bedrock-samples/issues/33

### What is your reasoning for including this mod?

Some people have beaten the 'Hard' level so there should be a harder level then that.

**Comment by lrmtheboss** [comment]
This issue is invalid, you have linked to a Mojang repo and not a mod. This type of mod is also not relevant to our list here at TUL

**Comment by skanda890** [comment]
Oh, Okay.
