### ISSUE TITLE
[Correction] Fastload is buggy/incompatible on 1.20.1+ (and unmaintained)

### ISSUE THREAD

**Issue by JL2210** [TheUsefulLists/UsefulMods#275]
### Checklist

- [X] I've checked that this correction is valid and accurate.
- [X] I've checked that this correction has not already been suggested.

### What mod is this correction for?

Fastload

### What section(s) of the list is this correction for?

Performance

### What version(s) does this correction apply to?

1.20.X (Fabric)

### What needs correcting?

Fastload causes the game to fail to capture the mouse for ~10 seconds alone or forever with other mods on 1.20.1+.
It is also unmaintained per the author's Modrinth. Would recommend removal from at least the 1.20 list.

### Input relevant link(s) which can be used to verify the correction.

https://github.com/BumbleSoftware/Fastload/issues/101
https://modrinth.com/mod/fastload

**Comment by GlitchTime** [comment]
> I fixed this problem by accident: I turned off the local radius and server radius in the mod settings and turned on instant loading just in case. This bug does not appear with these settings.

Can confirm, also works without instant load. ¯\_(ツ)_/¯

**Comment by Felix14-v2** [comment]
Anyways, ModernFix has a setting for similar optimisation and works without compatibility issues, with which FastLoad is full of.
