### ISSUE TITLE
Optifine on older versions [Correction]

### ISSUE THREAD

**Issue by Brody0727** [TheUsefulLists/UsefulMods#277]
### Checklist

- [X] I've checked that this correction is valid and accurate.
- [X] I've checked that this correction has not already been suggested.

### What mod is this correction for?

Optifine

### What section(s) of the list is this correction for?

Performance

### What version(s) does this correction apply to?

1.8.X or earlier

### What needs correcting?

Just adding Optifine or at least adding a notice on this. Optifine is great before 1.13, as there's nothing replacing it without Fabric. Plus, Optifine is completely compatible with every single mod listed there, so it's probably a good idea to add a notice on the "Notes on Optifine" document, stating that Optifine is a good idea for usage before 1.13, because there's absolutely no reason to not use it as a performance mod.

### Input relevant link(s) which can be used to verify the correction.

None

**Comment by Radk6** [comment]
> Optifine is great before 1.13, as there's nothing replacing it without Fabric.

That's not entirely true. There's [Vintagium](https://github.com/Asek3/sodium-1.12) for 1.12.2 and [Angelica](https://github.com/GTNewHorizons/Angelica) on 1.7.10. Both of these are Forge mods.

**Comment by Poopooracoocoo** [comment]
Neither are full replacements for OptiFine's set of features. Angelica is getting there though.
