### ISSUE TITLE
[Addition] KoTRT Core

### ISSUE THREAD

**Issue by GeefireMC** [TheUsefulLists/UsefulMods#5]
**Mod Name:** 
KoTRT Core

**Mod Links:**
https://www.curseforge.com/minecraft/mc-mods/kotrt-core
https://github.com/TeamDeusVult/KoTRT_Core

**Suggested Lists:**
Performance 1.16
Bugfixes 1.16

**Reasoning for Inclusion:**
In its readme it claims that it can improve performance up to 4X in large modpacks, and it claims that it features bugfixes for several mods.

**Other Information:**
N/A

PS: Seeing as this is the first issue in the repository, I've tried to make a good format for further mod suggestions. If issues isn't the right place to suggest mods, this should probably be deleted.
Edit: apparently pull requests count as issues to github, so this is the 5th issue. oops.

**Comment by NordicGamerFE** [comment]
It will be added eventually i first have to go thru my doc then I can add it after I find out all the game features it actually removes

**Comment by viceversagames** [comment]
Hey! Dev of KoTRT here. In its current state it's not really production ready, it started out as a core mod for my modpacks and so it's not exactly designed for most other people to use. 

The core tech (smartly disabling entity ticks outside X blocks from players) does work though, especially at high render distances with modded entities. 

It's being rewritten right now into a mod called _Does It Tick?_ which will be something I'll be able to recommend inclusion in large modpacks.

**Comment by NordicGamerFE** [comment]
@viceversagames Just keep us updated when its done or make a pull request and we will get that added once its done :D

**Comment by Radplay** [comment]
This can be closed now, KoTRT Core is now called Doest It Tick?, which is already listed under Performance 1.16.x.
