### ISSUE TITLE
[Addition] Magnesium/Rubidium Extras

### ISSUE THREAD

**Issue by WolfBV** [TheUsefulLists/UsefulMods#58]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

Magnesium/Rubidium Extras

### What is your mod's main version?

1.16.X (Forge)

### Input a link to your suggested mod. Make sure it isn't hosted on a site listed on StopModReposts.

https://www.curseforge.com/minecraft/mc-mods/magnesium-extras

### What is your reasoning for including this mod?

Improves the performance of the Magnesium mod

### (OPTIONAL) Give some extra information about the mod.

Incompatible with Out of Sight if this mod’s Entity Culling isn’t disabled in the config.

**Comment by Radplay** [comment]
This can be closed, the mod is already on the list
