### ISSUE TITLE
[Correction] Sodium is no longer incompatible with Better Biome Blend

### ISSUE THREAD

**Issue by Rajbir98** [TheUsefulLists/UsefulMods#66]
Sodium Compatibility is added in 1.18.2-1.3.5

**Comment by lrmtheboss** [comment]
Can you please provide documentation or links that supports this

**Comment by tajemniktv** [comment]
![image](https://user-images.githubusercontent.com/12156943/175846860-5d3e1f45-a565-4137-ad5a-151ca27c98b7.png)
https://www.curseforge.com/minecraft/mc-mods/better-biome-blend
