### ISSUE TITLE
[Addition] 1.14 mods

### ISSUE THREAD

**Issue by Ohheffgee** [TheUsefulLists/UsefulMods#69]
### Checklist

- [X] I've checked that my mod suggestion hasn't already been added to one of the lists.
- [X] I've checked the latest issues to make sure that this mod hasn't already been suggested.

### What is your mod's name?

Read title.

### What is your mod's main version?

Other (Forge)

### Input a link to your suggested mod. Make sure it isn't hosted on a site listed on StopModReposts.

Read title.

### What is your reasoning for including this mod?

Many people play versions like 1.14 including me, and I think it'd be a good addition to put a list with 1.14 mods.

**Comment by NordicGamerFE** [comment]
For sure want to support most of the version and this is definitely something we will add sometime, But right now we don't have the workforce to maintain more versions. Tho if someone want to pull request 1.14 that's definitely something that can be done sooner then if the team has to add it.
